# IMPORTANT REFERENCE: https://www.youtube.com/watch?v=uimdXPZc40I&list=PLkrJrLs7xfbXcEKhTCKRSr2VXH4yiBeXo&index=4
project:
  type: website
  output-dir: docs
  

website:
  title: "MGMT 47400: Predictive Analytics"
  sidebar:
    background: primary
    logo: "images/mgmt_474_ai_logo_02-modified.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/davi-moreira/2025S_predictive_analytics_MGMT474
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule and Material

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
editor: visual

