---
title: "Schedule"
author: "Davi Moreira"
editor: visual
---

<style>
  .overflow-table {
    font-size: 0.85rem; /* Smaller font for compact display */
    width: 100%; /* Ensure the table fits within page width */
    line-height: 1.2; /* Tighter line spacing */
  }
  .overflow-table th, .overflow-table td {
    padding: 0.3rem; /* Reduce padding for compact layout */
    text-align: left; /* Left-align for readability */
    word-wrap: break-word; /* Wrap long text within cells */
    vertical-align: top; /* Align cell content to the top */
  }
  .overflow-table th:nth-child(1), .overflow-table td:nth-child(1) {
    width: 7%; /* Increase width of the first column */
  }
  .below-table {
    font-size: 0.85rem; /* Match the font size of the table */
    line-height: 1.2; /* Match line height */
    margin-top: 1rem; /* Add spacing above the text */
  }
</style>

::: {.overflow-table}

| Week | Topic | Readings [ISLP](#) | Material\* | Supplementary Materials |
|----------|----------|----------|----------|-----------------------------------|
| Week 1 | Syllabus, Logistics, and Introduction. | Ch. 1; Ch. 2; | [slides](/lecture_slides/01_introduction/01_introduction.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch02-statlearn-lab.ipynb){target="_blank"} | \- [**Video**: Statistical Learning: 2.1 Introduction to Regression Models](https://www.youtube.com/watch?v=ox0cKk7h4o0&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=5){target="_blank"}<br>- [**Video**: Statistical Learning: 2.2 Dimensionality and Structured Models](https://www.youtube.com/watch?v=uFwbrdvrAJs&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=5){target="_blank"}<br>- [**Video**: Statistical Learning: 2.3 Model Selection and Bias Variance Tradeoff](https://www.youtube.com/watch?v=pvcEQfcO3pk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=6){target="_blank"}<br>- [**Video**: Statistical Learning: 2.4 Classification](https://www.youtube.com/watch?v=BMJQ3LQ_QKU&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=7){target="_blank"}<br>- [**Video**: Statistical Learning: 2.Py Data Types, Arrays, and Basics - 2023](https://www.youtube.com/watch?v=Cv1sx_HNRHM&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=3){target="_blank"}<br>- [**Video**: Statistical Learning: 2.Py.3 Graphics - 2023](https://www.youtube.com/watch?v=JykmuvCY130&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=4){target="_blank"}<br>- [**Video**: Statistical Learning: 2.Py Indexing and Dataframes - 2023](https://www.youtube.com/watch?v=Zcb-1JmmO_U&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=5){target="_blank"} |
| Week 2 | Linear Regression | Ch. 3. | [slides](/lecture_slides/03_linear_regression/03_linear_regression.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch03-linreg-lab.ipynb){target="_blank"} | \- [**Video**: Statistical Learning: 3.1 Simple linear regression](https://www.youtube.com/watch?v=vCHtY6Me5FI&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=9){target="_blank"}<br>- [**Video**: Statistical Learning: 3.2 Hypothesis Testing and Confidence Intervals](https://www.youtube.com/watch?v=3GiWpRfkSjc&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=10){target="_blank"}<br>- [**Video**: Statistical Learning: 3.3 Multiple Linear Regression](https://www.youtube.com/watch?v=o9hoLdylWKo&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=11){target="_blank"}<br>- [**Video**: Statistical Learning: 3.4 Some important questions](https://www.youtube.com/watch?v=50sv4UTjE90&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=12){target="_blank"}<br>- [**Video**: Statistical Learning: 3.5 Extensions of the Linear Model](https://www.youtube.com/watch?v=dEBQmiXv9fk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=13){target="_blank"}<br>- [**Video**: Statistical Learning: 3.Py Linear Regression and statsmodels Package - 2023](https://www.youtube.com/watch?v=mKalBNrxToU&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=6){target="_blank"}<br>- [**Video**: Statistical Learning: 3.Py Multiple Linear Regression Package - 2023](https://www.youtube.com/watch?v=pGOr3HZhUZQ&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=7){target="_blank"}<br>- [**Video**: Statistical Learning: 3.Py Interactions, Qualitative Predictors and Other Details I 2023](https://www.youtube.com/watch?v=d0K2mDclyXM&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=8){target="_blank"} |
| Week 3 | Classification | Ch. 4 | [slides](/lecture_slides/04_classification/04_classification.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch04-classification-lab.ipynb){target="_blank"} | \- [**Video**: Statistical Learning: 4.1 Introduction to Classification Problems](https://www.youtube.com/watch?v=ju3J7iRy6xI&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=16){target="_blank"}<br>- [**Video**: Statistical Learning: 4.2 Logistic Regression](https://www.youtube.com/watch?v=kr_Be9NVXOM&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=16){target="_blank"}<br>- [**Video**: Statistical Learning: 4.3 Multivariate Logistic Regression](https://www.youtube.com/watch?v=1uJVE8bkabc&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=17){target="_blank"}<br>- [**Video**: Statistical Learning: 4.4 Logistic Regression Case Control Sampling and Multiclass](https://www.youtube.com/watch?v=sYDDk6R-be0&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=18){target="_blank"}<br>- [**Video**: Statistical Learning: 4.5 Discriminant Analysis](https://www.youtube.com/watch?v=oJc2r246VoQ&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=19){target="_blank"}<br>- [**Video**: Statistical Learning: 4.6 Gaussian Discriminant Analysis (One Variable)](https://www.youtube.com/watch?v=14JVlzWHKgk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=20){target="_blank"}<br>- [**Video**: Statistical Learning: 4.7 Gaussian Discriminant Analysis (Many Variables)](https://www.youtube.com/watch?v=aUlTqhDtpnw&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=21){target="_blank"}<br>- [**Video**: Statistical Learning: 4.8 Generalized Linear Models](https://www.youtube.com/watch?v=n8Nj64FyjSo&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=22){target="_blank"}<br>- [**Video**: Statistical Learning: 4.9 Quadratic Discriminant Analysis and Naive Bayes](https://www.youtube.com/watch?v=giCZkipHEmA&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=23){target="_blank"}<br>- [**Video**: Statistical Learning: 4.Py Logistic Regression I 2023](https://www.youtube.com/watch?v=wOGBlLLuc4I&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=9){target="_blank"}<br>- [**Video**: Statistical Learning: 4.Py Linear Discriminant Analysis (LDA) I 2023](https://www.youtube.com/watch?v=9pfRgzM1oCQ&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=10){target="_blank"}<br>- [**Video**: Statistical Learning: 4.Py K-Nearest Neighbors (KNN) I 2023](https://www.youtube.com/watch?v=yLEx1FnYyOo&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=11){target="_blank"} |
| Week 4 | Resampling Methods | Ch. 5 | [slides](/lecture_slides/05_resampling_methods/05_resampling_methods.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch05-resample-lab.ipynb){target="_blank"} | \- [**Video**: Statistical Learning: 5.1 Cross Validation](https://www.youtube.com/watch?v=6eWODQJrMKs&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=27){target="_blank"}<br>- [**Video**: Statistical Learning: 5.2 K-fold Cross Validation](https://www.youtube.com/watch?v=AMfvd_hLssE&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=28){target="_blank"}<br>- [**Video**: Statistical Learning: 5.3 Cross Validation the wrong and right way](https://www.youtube.com/watch?v=jgoa28FR__Y&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=29){target="_blank"}<br>- [**Video**: Statistical Learning: 5.4 The Bootstrap](https://www.youtube.com/watch?v=h_LweqiIotE&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=30){target="_blank"}<br>- [**Video**: Statistical Learning: 5.5 More on the Bootstrap](https://www.youtube.com/watch?v=OKREmw6YP64&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=31){target="_blank"}<br>- [**Video**: Statistical Learning: 5.Py Cross-Validation I 2023](https://www.youtube.com/watch?v=oYzo95sFoSY&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=12){target="_blank"}<br>- [**Video**: Statistical Learning: 5.Py Bootstrap I 2023](https://www.youtube.com/watch?v=1BxtC6ZOvJQ&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=13){target="_blank"}<br>- [**Book Chapter**: Modern Dive -Bootstrapping and Confidence Intervals](https://moderndive.com/8-confidence-intervals.html){target="_blank"}|
| Week 5 | Linear Model Selection & Regularization | Ch. 6 | [slides](/lecture_slides/06_model_selection/06_model_selection.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch06-varselect-lab.ipynb){target="_blank"} | \- [**Video**: Statistical Learning: 6.1 Introduction and Best Subset Selection](https://www.youtube.com/watch?v=nsv5rEV3mVI&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=34){target="_blank"}<br>- [**Video**: Statistical Learning: 6.2 Stepwise Selection](https://www.youtube.com/watch?v=ynXq-Gw1xfE&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=35){target="_blank"}<br>- [**Video**: Statistical Learning: 6.3 Backward stepwise selection](https://www.youtube.com/watch?v=c5aI9cowjRI&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=36){target="_blank"}<br>- [**Video**: Statistical Learning: 6.4 Estimating test error](https://www.youtube.com/watch?v=48P-oV6cH44&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=37){target="_blank"}<br>- [**Video**: Statistical Learning: 6.5 Validation and cross validation](https://www.youtube.com/watch?v=mzb5Xs58bb0&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=38){target="_blank"}<br>- [**Video**: Statistical Learning: 6.6 Shrinkage methods and ridge regression](https://www.youtube.com/watch?v=lLlG5xkyqIA&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=39){target="_blank"}<br>- [**Video**: Statistical Learning: 6.7 The Lasso](https://www.youtube.com/watch?v=0tfPuddPhEY&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=40){target="_blank"}<br>- [**Video**: Statistical Learning: 6.8 Tuning parameter selection](https://www.youtube.com/watch?v=KV1Kt6I8rYs&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=41){target="_blank"}<br>- [**Video**: Statistical Learning: 6.9 Dimension Reduction Methods](https://www.youtube.com/watch?v=bpto4g5l_go&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=42){target="_blank"}<br>- [**Video**: Statistical Learning: 6.10 Principal Components Regression and Partial Least Squares](https://www.youtube.com/watch?v=Uo19ST0IEZI&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=43){target="_blank"}<br>- [**Video**: Statistical Learning: 6.Py Stepwise Regression I 2023](https://www.youtube.com/watch?v=EJ-haQArGzU&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=14){target="_blank"}<br>- [**Video**: Statistical Learning: 6.Py Ridge Regression and the Lasso I 2023](https://www.youtube.com/watch?v=dI7xi5kRwwM&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=15){target="_blank"} |
| Week 6 | Beyond Linearity | Ch. 7 | [slides](/lecture_slides/07_beyond_linearity/07_beyond_linearity.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch07-nonlin-lab.ipynb){target="_blank"} | \- [**Video**: Statistical Learning: 7.1 Polynomials and Step Functions](https://www.youtube.com/watch?v=F-D3lZzYn50&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=48){target="_blank"}<br>- [**Video**: Statistical Learning: 7.2 Piecewise Polynomials and Splines](https://www.youtube.com/watch?v=FrVaxvwCLYM&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=49){target="_blank"}<br>- [**Video**: Statistical Learning: 7.3 Smoothing Splines](https://www.youtube.com/watch?v=b_HSFOnrGLI&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=50){target="_blank"}<br>- [**Video**: Statistical Learning: 7.4 Generalized Additive Models and Local Regression](https://www.youtube.com/watch?v=3aMB51GMUyQ&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=51){target="_blank"}<br>- [**Video**: Statistical Learning: 7.Py Polynomial Regressions and Step Functions I 2023](https://www.youtube.com/watch?v=_0omkfNiU2c&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=16){target="_blank"}<br>- [**Video**: Statistical Learning: 7.Py Splines I 2023](https://www.youtube.com/watch?v=C9h-o6AfNX0&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=17){target="_blank"}<br>- [**Video**: Statistical Learning: 7.Py Generalized Additive Models (GAMs) I 2023](https://www.youtube.com/watch?v=hQx84r2maaE&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=18){target="_blank"} |
| Week 7 | Tree-Based Methods | Ch. 8 | [slides](/lecture_slides/08_tree_based_methods/08_tree_based_methods.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch08-baggboost-lab.ipynb){target="_blank"} | \- [**Video**: Statistical Learning: 8.1 Tree based methods](https://www.youtube.com/watch?v=QNnayf--_yk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=54){target="_blank"}<br>- [**Video**: Statistical Learning: 8.2 More details on Trees](https://www.youtube.com/watch?v=JaoTOfTNOVk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=55){target="_blank"}<br>- [**Video**: Statistical Learning: 8.3 Classification Trees](https://www.youtube.com/watch?v=gLcfKSMKOb0&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=56){target="_blank"}<br>- [**Video**: Statistical Learning: 8.4 Bagging](https://www.youtube.com/watch?v=_cKAxjnInfA&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=57){target="_blank"}<br>- [**Video**: Statistical Learning: 8.5 Boosting](https://www.youtube.com/watch?v=cdl4C2eCOHk&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=58){target="_blank"}<br>- [**Video**: Statistical Learning: 8.6 Bayesian Additive Regression Trees](https://www.youtube.com/watch?v=xWhPwHZF4c0&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=59){target="_blank"}<br>- [**Video**: Statistical Learning: 8.Py Tree-Based Methods I 2023](https://www.youtube.com/watch?v=AVTfC5WnDTo&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=19){target="_blank"} |
| Week 8 | Support Vector Machines | Ch. 9 | [slides](/lecture_slides/09_support_vector_machines/09_support_vector_machines.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch09-svm-lab.ipynb){target="_blank"} | \- [**Video**: Statistical Learning: 9.1 Optimal Separating Hyperplane](https://www.youtube.com/watch?v=Op0OyOuDjcQ&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=62){target="_blank"}<br>- [**Video**: Statistical Learning: 9.2.Support Vector Classifier](https://www.youtube.com/watch?v=pjvnCEfAswc&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=63){target="_blank"}<br>- [**Video**: Statistical Learning: 9.3 Feature Expansion and the SVM](https://www.youtube.com/watch?v=02icdqOJsH4&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=64){target="_blank"}<br>- [**Video**: Statistical Learning: 9.4 Example and Comparison with Logistic Regression](https://www.youtube.com/watch?v=m5d7-URGnVY&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=65){target="_blank"}<br>- [**Video**: Statistical Learning: 9.Py Support Vector Machines I 2023](https://www.youtube.com/watch?v=94wKFGS4Zm4&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=20){target="_blank"}<br>- [**Video**: Statistical Learning: 9.Py ROC Curves I 2023](https://www.youtube.com/watch?v=1fmHMmoa47g&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=21){target="_blank"} |
| Week 09 | Unsupervised Learning | Ch. 12 | [slides](/lecture_slides/12_unsupervised_learning/12_unsupervised_learning.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch12-unsup-lab.ipynb){target="_blank"} | \- [**Video**: Statistical Learning: 12.1 Principal Components](https://www.youtube.com/watch?v=kpuQqOzQXfM&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=86){target="_blank"}<br>- [**Video**: Statistical Learning: 12.2 Higher order principal components](https://www.youtube.com/watch?v=O30nHhyBiAs&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=87){target="_blank"}<br>- [**Video**: Statistical Learning: 12.3 k means Clustering](https://www.youtube.com/watch?v=ded_NQqOe7I&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=88){target="_blank"}<br>- [**Video**: Statistical Learning: 12.4 Hierarchical Clustering](https://www.youtube.com/watch?v=yktzn-Mr2Nw&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=89){target="_blank"}<br>- [**Video**: Statistical Learning: 12.5 Matrix Completion](https://www.youtube.com/watch?v=MYKb5KcI55s&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=90){target="_blank"}<br>- [**Video**: Statistical Learning: 12.6 Breast Cancer Example](https://www.youtube.com/watch?v=InBhMLEx6sU&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=91){target="_blank"}<br>- [**Video**: Statistical Learning: 12.Py Principal Components I 2023](https://www.youtube.com/watch?v=3zpISnhksqQ&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=28){target="_blank"}<br>- [**Video**: Statistical Learning: 12.Py Clustering I 2023](https://www.youtube.com/watch?v=xhLD4nEEVlE&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=29){target="_blank"}<br>- [**Video**: Statistical Learning: 12.Py Application: NCI60 Data I 2023](https://www.youtube.com/watch?v=aygQSHAbMFQ&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=30){target="_blank"} |
| Week 10 | Final Project | . | [slides](/lecture_slides/99_data_communication_poster/99_data_communication_poster.html){target="_blank"}| [Poster Template](docs/lecture_slides/99_data_communication_poster/2025S_mgmt474_poster_template.pptx.zip){target="_blank"}<br>[Rubric](https://www.purdue.edu/undergrad-research/conferences/spring/Rubric_Poster.pdf){target="_blank"}<br>[Video: Creating a Professional Poster](https://www.youtube.com/watch?v=ReN-QcVTZ1o){target="_blank"} |
| Week 11 | Final Project | . | . | . |
| Week 12 | Final Project | . | . | . |
| Week 13 | Deep Learning | Ch. 10 | [slides - TBP](/lecture_slides/10_deep_learning/10_deep_learning.html){target="_blank"}<br>[book lab](https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch10-deeplearning-lab.ipynb){target="_blank"} | \- [**Video**: Statistical Learning: 10.1 Introduction to Neural Networks](https://www.youtube.com/watch?v=jJb2qytbcNg&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=68){target="_blank"}<br>- [**Video**: Statistical Learning: 10.2 Convolutional Neural Networks](https://www.youtube.com/watch?v=ggOZuZnA6is&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=69){target="_blank"}<br>- [**Video**: Statistical Learning: 10.3 Document Classification](https://www.youtube.com/watch?v=Zw3L-0ZP_DA&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=70){target="_blank"}<br>- [**Video**: Statistical Learning: 10.4 Recurrent Neural Networks](Statistical Learning: 10.5 Time Series Forecasting){target="_blank"}<br>- [**Video**: Statistical Learning: 10.6 Fitting Neural Networks](https://www.youtube.com/watch?v=07zslA8BXZY&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=73){target="_blank"}<br>- [**Video**: Statistical Learning: 10.7 Interpolation and Double Descent](https://www.youtube.com/watch?v=qRHdQz_P_Lo&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=74){target="_blank"}<br>- [**Video**: Statistical Learning: 10.Py Single Layer Model: Hitters Data I 2023](https://www.youtube.com/watch?v=-ZHEnz-emcQ&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=22){target="_blank"}<br>- [**Video**: Statistical Learning: 10.Py Multilayer Model: MNIST Digit Data I 2023](https://www.youtube.com/watch?v=csmHZGEsONU&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=23){target="_blank"}<br>- [**Video**: Statistical Learning: 10.Py Convolutional Neural Network: CIFAR Image Data I 2023](https://www.youtube.com/watch?v=NJ0gKDGdchQ&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=24){target="_blank"}<br>- [**Video**: Statistical Learning: 10.Py Document Classification and Recurrent Neural Networks I 2023](https://www.youtube.com/watch?v=RM-MkwkGUSI&list=PLoROMvodv4rNHU1-iPeDRH-J0cL-CrIda&index=25){target="_blank"} |
| Week 14 | Deep Learning | Ch. 10 | . | . |
| Week 15 | Deep Learning | Ch. 10 | . | . |

\* The course slides and labs are based on the **[ISLP](#)** book, [*"An Introduction to Statistical Learning with Applications in Python"*](https://www.statlearning.com/){target="_blank"} by James, G., Witten, D., Hastie, T., and Tibshirani, R., and have been adapted to suit the specific needs of our course.

:::